// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
window.wailsbindings = {"main":{"App":{"Greet":{"name":"main.App.Greet","inputs":[{"type":"string"}],"outputs":[{"type":"string"}]}},"Updater":{"CheckForUpdate":{"name":"main.Updater.CheckForUpdate","outputs":[{"type":"string"}]}}}};
const go = {
  "main": {
    "App": {
      /**
       * Greet
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "Greet": (arg1) => {
        return window.go.main.App.Greet(arg1);
      },
    },
    "Updater": {
      /**
       * CheckForUpdate
       * @returns {Promise<string>}  - Go Type: string
       */
      "CheckForUpdate": () => {
        return window.go.main.Updater.CheckForUpdate();
      },
    },
  },

};
export default go;
